### PR TITLE
Extra flags for plog converter

### PR DESCRIPTION
**Pull request by asapelkin**

### CODE REVIEW

**Comment by asapelkin** [comment]
@pavel-belikov, need review, please.

**Comment by asapelkin** [comment]
@pavel-belikov, @SvyatoslavRazmyslov  still need a review)

**Comment by SvyatoslavRazmyslov** [comment]
Hi @asapelkin,

Unfortunately, our developers are busy at the moment. Is it OK if we review this PR on Monday?

**Comment by asapelkin** [comment]
Thanks, of course OK!

**Comment by KonstantinKochkin** [comment]
Hi @asapelkin,
Thanks for the PR, your code has been reviewed and approved.

**Pull request merged**
